export const editorStyles = `
  prose cursor-auto max-w-none outline-none border-none p-2 rounded-lg bg-transparent
  prose-headings:text-white
  prose-heading-h1:font-bold
  prose-cursor:text-[#F84E4E]
  prose-p:text-gray-400
  prose-strong:text-white
  prose-em:text-gray-300
  prose-code:text-[#F84E4E]
  prose-code:bg-[#374151]
  prose-code:rounded-sm
  prose-code:mx-1
  prose-code:p-0.5
  prose-pre:bg-[#374151]
  prose-pre:rounded-md
  prose-pre:px-2
  prose-pre:py-1
  focus:outline-none
  focus:ring-0
  focus:border-none
  prose-blockquote:text-gray-400
  prose-blockquote:font-medium
  prose-blockquote:border-[#F84E4E]
  prose-blockquote:border-l-2
  prose-ul:text-gray-300
  prose-ul:font-medium
  prose-ol:text-gray-300
  prose-li:text-[#F84E4E]/80
  prose-li:marker:text-[#F84E4E]
  prose-a:text-[#F84E4E]
  hover:prose-a:text-[#F84E4E]
  prose-img:rounded-lg
  prose-img:border
  prose-img:border-gray-700
  prose-a:mx-1
  prose-a:cursor-pointer
  prose-a:relative
  prose-a:hover:after:content-[attr(data-link)]
  prose-a:hover:after:absolute
  prose-a:hover:after:left-1/2
  prose-a:hover:after:-translate-x-1/2
  prose-a:hover:after:top-full
  prose-a:hover:after:mt-1.5
  prose-a:hover:after:px-2
  prose-a:hover:after:py-1
  prose-a:hover:after:bg-[#374151]
  prose-a:hover:after:text-white
  prose-a:hover:after:text-sm
  prose-a:hover:after:rounded
  prose-a:hover:after:whitespace-nowrap
  prose-a:hover:after:z-[9999]
  prose-a:hover:after:max-w-xs
  prose-a:hover:after:overflow-hidden
  prose-a:hover:after:text-ellipsis
  prose-hr:border-gray-700
  prose-hr:my-6
`
